columns:
  season: int
  year: int
  month: int
  hour: int
  holiday: int
  weekday: int
  workingday: int
  weather: int
  temp: float
  humidity: float
  windspeed: float
  count : int


numerical_columns:
  - temp
  - humidity
  - windspeed

categorical_columns:
  - season
  - year
  - month
  - hour
  - holiday
  - weekday
  - workingday
  - weather

target_column: count

domain_value:
  season:
    - 1
    - 2
    - 3
    - 4



  


